# Trabajo Práctico Redes Neuronales

Trabajo Práctico hecho por Benjamin Kapustiansky y Oliver Safdieh

In [1]:
%pip install pandas
%pip install numpy
%pip install matplotlib
%pip install tabulate
%pip install networkx
%pip install random
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement random (from versions: none)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for random


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import HTML, display
import tabulate
import networkx as nx
from random import random as rand
import itertools

from sklearn.preprocessing import StandardScaler

## Funciones

In [3]:
def sigmoid(x):
    return 1 / ( 1 + np.exp(-x) )

# sigmoid = lambda x : 1 / ( 1 + np.exp(-x) )

def sigmoid_derivative(x):
    return x * (1 - x)

# sigmoid_derivative = lambda x : x * (1 - x)

## Dataset

In [4]:
archivo = "dataset_frutas.csv"

# Leer datos del archivo
frutas : pd.DataFrame = pd.read_csv(archivo)
frutas

Peso      Color    Tamaño  Ácida  Dulce  Tropical
0    202.921570       Rojo  5.666598      0      1         1
1    162.004716      Verde  8.298573      1      1         1
2    179.362140   Amarillo  5.631649      0      1         1
3    217.226796   Amarillo  8.166169      0      0         1
4    206.026740      Claro  7.444632      0      0         1
..          ...        ...       ...    ...    ...       ...
295  184.106741     Oscuro  3.981108      1      0         0
296  152.931749       Rojo  7.602139      1      1         0
297  167.488610  Muy claro  7.751694      0      0         1
298  138.016529      Verde  5.637248      1      1         1
299  161.101677   Amarillo  8.441367      0      1         1

[300 rows x 6 columns]

## One Hot Encoding

In [5]:
# Color
frutas = pd.get_dummies(frutas, columns=["Color"])

frutas

Peso    Tamaño  Ácida  Dulce  Tropical  Color_Amarillo  \
0    202.921570  5.666598      0      1         1           False   
1    162.004716  8.298573      1      1         1           False   
2    179.362140  5.631649      0      1         1            True   
3    217.226796  8.166169      0      0         1            True   
4    206.026740  7.444632      0      0         1           False   
..          ...       ...    ...    ...       ...             ...   
295  184.106741  3.981108      1      0         0           False   
296  152.931749  7.602139      1      1         0           False   
297  167.488610  7.751694      0      0         1           False   
298  138.016529  5.637248      1      1         1           False   
299  161.101677  8.441367      0      1         1            True   

     Color_Claro  Color_Muy claro  Color_Muy oscuro  Color_Naranja  \
0          False            False             False          False   
1          False            False             False          False   
2          False            False             False          False   
3          False            False             False          False   
4           True            False             False          False   
..           ...              ...               ...            ...   
295        False            False             False          False   
296        False            False             False          False   
297        False             True             False          False   
298        False            False             False          False   
299        False            False             False          False   

     Color_Oscuro  Color_Rojo  Color_Rojo claro  Color_Verde  
0           False        True             False        False  
1           False       False             False         True  
2           False       False             False        False  
3           False       False             False        False  
4           False       False             False        False  
..            ...         ...               ...          ...  
295          True       False             False        False  
296         False        True             False        False  
297         False       False             False        False  
298         False       False             False         True  
299         False       False             False        False  

[300 rows x 14 columns]

In [6]:
frutas.replace({True: 1, False: 0}, inplace=True)

frutas

C:\Users\benjo\AppData\Local\Temp\ipykernel_25172\4120693317.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frutas.replace({True: 1, False: 0}, inplace=True)


Peso    Tamaño  Ácida  Dulce  Tropical  Color_Amarillo  \
0    202.921570  5.666598      0      1         1               0   
1    162.004716  8.298573      1      1         1               0   
2    179.362140  5.631649      0      1         1               1   
3    217.226796  8.166169      0      0         1               1   
4    206.026740  7.444632      0      0         1               0   
..          ...       ...    ...    ...       ...             ...   
295  184.106741  3.981108      1      0         0               0   
296  152.931749  7.602139      1      1         0               0   
297  167.488610  7.751694      0      0         1               0   
298  138.016529  5.637248      1      1         1               0   
299  161.101677  8.441367      0      1         1               1   

     Color_Claro  Color_Muy claro  Color_Muy oscuro  Color_Naranja  \
0              0                0                 0              0   
1              0                0                 0              0   
2              0                0                 0              0   
3              0                0                 0              0   
4              1                0                 0              0   
..           ...              ...               ...            ...   
295            0                0                 0              0   
296            0                0                 0              0   
297            0                1                 0              0   
298            0                0                 0              0   
299            0                0                 0              0   

     Color_Oscuro  Color_Rojo  Color_Rojo claro  Color_Verde  
0               0           1                 0            0  
1               0           0                 0            1  
2               0           0                 0            0  
3               0           0                 0            0  
4               0           0                 0            0  
..            ...         ...               ...          ...  
295             1           0                 0            0  
296             0           1                 0            0  
297             0           0                 0            0  
298             0           0                 0            1  
299             0           0                 0            0  

[300 rows x 14 columns]

## Reordenar columnas

In [7]:
frutas.columns

Index(['Peso', 'Tamaño', 'Ácida', 'Dulce', 'Tropical', 'Color_Amarillo',
       'Color_Claro', 'Color_Muy claro', 'Color_Muy oscuro', 'Color_Naranja',
       'Color_Oscuro', 'Color_Rojo', 'Color_Rojo claro', 'Color_Verde'],
      dtype='object')

In [8]:
frutas = frutas.reindex(['Peso', 'Tamaño', 'Color_Amarillo',
       'Color_Claro', 'Color_Muy claro', 'Color_Muy oscuro', 'Color_Naranja',
       'Color_Oscuro', 'Color_Rojo', 'Color_Rojo claro', 'Color_Verde', 'Ácida', 'Dulce', 'Tropical'], axis=1)
frutas


Peso    Tamaño  Color_Amarillo  Color_Claro  Color_Muy claro  \
0    202.921570  5.666598               0            0                0   
1    162.004716  8.298573               0            0                0   
2    179.362140  5.631649               1            0                0   
3    217.226796  8.166169               1            0                0   
4    206.026740  7.444632               0            1                0   
..          ...       ...             ...          ...              ...   
295  184.106741  3.981108               0            0                0   
296  152.931749  7.602139               0            0                0   
297  167.488610  7.751694               0            0                1   
298  138.016529  5.637248               0            0                0   
299  161.101677  8.441367               1            0                0   

     Color_Muy oscuro  Color_Naranja  Color_Oscuro  Color_Rojo  \
0                   0              0             0           1   
1                   0              0             0           0   
2                   0              0             0           0   
3                   0              0             0           0   
4                   0              0             0           0   
..                ...            ...           ...         ...   
295                 0              0             1           0   
296                 0              0             0           1   
297                 0              0             0           0   
298                 0              0             0           0   
299                 0              0             0           0   

     Color_Rojo claro  Color_Verde  Ácida  Dulce  Tropical  
0                   0            0      0      1         1  
1                   0            1      1      1         1  
2                   0            0      0      1         1  
3                   0            0      0      0         1  
4                   0            0      0      0         1  
..                ...          ...    ...    ...       ...  
295                 0            0      1      0         0  
296                 0            0      1      1         0  
297                 0            0      0      0         1  
298                 0            1      1      1         1  
299                 0            0      0      1         1  

[300 rows x 14 columns]

In [9]:
# Seleccionar las columnas a escalar (por ejemplo, 'columna1' y 'columna2')
columnas_a_escalar = ['Peso', 'Tamaño']

# Crear el scaler y aplicarlo solo a las columnas seleccionadas
scaler = StandardScaler()
frutas[columnas_a_escalar] = scaler.fit_transform(frutas[columnas_a_escalar])

frutas.head()

Peso    Tamaño  Color_Amarillo  Color_Claro  Color_Muy claro  \
0  1.735306 -0.712196               0            0                0   
1  0.372366  0.629630               0            0                0   
2  0.950542 -0.730013               1            0                0   
3  2.211812  0.562128               1            0                0   
4  1.838739  0.194277               0            1                0   

   Color_Muy oscuro  Color_Naranja  Color_Oscuro  Color_Rojo  \
0                 0              0             0           1   
1                 0              0             0           0   
2                 0              0             0           0   
3                 0              0             0           0   
4                 0              0             0           0   

   Color_Rojo claro  Color_Verde  Ácida  Dulce  Tropical  
0                 0            0      0      1         1  
1                 0            1      1      1         1  
2                 0            0      0      1         1  
3                 0            0      0      0         1  
4                 0            0      0      0         1

In [10]:
training_inputs = np.array(frutas[['Peso', 'Tamaño', 'Color_Amarillo', 'Color_Claro', 'Color_Muy claro', 'Color_Muy oscuro', 'Color_Naranja', 'Color_Oscuro', 'Color_Rojo', 'Color_Rojo claro', 'Color_Verde']])
training_outputs = np.array(frutas[['Ácida', 'Dulce', 'Tropical']]).T

display(training_inputs)
display(training_outputs)

array([[ 1.73530578, -0.71219616,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.37236649,  0.62963036,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 0.95054178, -0.73001346,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.55503485,  0.35082207,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.42667937, -0.72715926,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 0.34228626,  0.7024294 ,  1.        , ...,  0.        ,
         0.        ,  0.        ]])

array([[0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
        1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
        1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
        1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
        1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
        0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 

In [11]:
# training_values = np.concatenate((training_inputs.T, training_outputs.T)).T
# table = lambda arr : display(HTML(tabulate.tabulate(arr, tablefmt='html')))
# table(training_values)

## Estructura

In [12]:
input = training_inputs.shape[1]
input

11

In [13]:
output = training_outputs.shape[0]
output

3

La estructura de la red son 11 neuronas de entrada y 3 de salida. No hay capas intermedias.

## Weights

Definiendo pesos random para partir de una base para hacer el entrenamiento. De tamaño tiene las variables input y output. Es una matriz de ancho (output) y alto (input).

In [14]:
synaptic_weights = np.random.random((input, output))

synaptic_weights

array([[0.98757434, 0.18778816, 0.43766156],
       [0.2300674 , 0.68361367, 0.26019725],
       [0.78088201, 0.57663659, 0.6993807 ],
       [0.79176485, 0.7168149 , 0.29164495],
       [0.73694794, 0.7260266 , 0.71843186],
       [0.79508222, 0.48324237, 0.07203634],
       [0.17095851, 0.91398605, 0.1995538 ],
       [0.80420655, 0.83066418, 0.77855269],
       [0.65246236, 0.67106893, 0.33210921],
       [0.60296002, 0.76157701, 0.59682905],
       [0.62653818, 0.02724845, 0.34976292]])

## Funcion Fordward

Fordward propagation, avanza sobre la red primero calculando la multiplicacion punto entre el input (x) y el peso corrrespondiente al mismo (w). Por ultimo pasa por la funcion de activacion sigmoide.

In [15]:
forward = lambda x, w: sigmoid(np.dot(x, w))

Ejemplo de fordward

In [16]:
input_layer = training_inputs

# Genera un output haciendo la suma de los valores de input multiplicados por su peso sinaptico, y aplicandole la función sigmoide para normalizar a -1, 1
outputs = forward(input_layer, synaptic_weights)

outputs

array([[0.90046058, 0.6248233 , 0.71223718],
       [0.75752082, 0.6289228 , 0.66297083],
       [0.82515341, 0.56367486, 0.71615103],
       [0.95666691, 0.79839087, 0.85980487],
       [0.93415586, 0.76761958, 0.75895165],
       [0.391398  , 0.49563349, 0.51693232],
       [0.81032841, 0.57907186, 0.71117277],
       [0.63231504, 0.58863037, 0.63432579],
       [0.64806777, 0.57293082, 0.48802562],
       [0.53281205, 0.43662604, 0.47373439],
       [0.76171872, 0.84152037, 0.75402671],
       [0.80677163, 0.17527646, 0.45530236],
       [0.8185807 , 0.64212925, 0.59364002],
       [0.67764229, 0.57771191, 0.54302901],
       [0.68447039, 0.42422971, 0.61731935],
       [0.69845067, 0.65145009, 0.65859333],
       [0.89710144, 0.62942444, 0.65167054],
       [0.68803778, 0.77647685, 0.70447971],
       [0.5961357 , 0.68552898, 0.5628596 ],
       [0.42838914, 0.63012814, 0.5466457 ],
       [0.11583396, 0.80993304, 0.36798363],
       [0.75652546, 0.44300504, 0.50751344],
       [0.

In [17]:
training_outputs = training_outputs.T
training_outputs

array([[0, 1, 1],
       [1, 1, 1],
       [0, 1, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 1],
       [1, 1, 0],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [0, 1, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 1, 0],
       [1, 1, 0],
       [1, 0, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 0],
       [1, 1, 0],
       [1, 0, 0],
       [0, 1, 1],
       [1, 0, 0],
       [0, 1, 1],
       [1, 1, 0],
       [1, 0, 0],
       [1, 1, 1],
       [1, 1, 0],
       [0, 1, 1],
       [0, 1, 0],
       [0, 0, 0],
       [1, 0, 1],
       [1, 1, 1],
       [1, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 1, 1],
       [0, 1, 1],
       [0, 0, 0],
       [1, 0, 1],
       [0, 0, 1],
       [1, 1, 0],
       [1, 0, 0],
       [1, 1, 1],
       [1,

## Train

En una iteración de 25000 veces, genera un output aplicando la funcion fordward y la funcion sigmoide para la activacion de la misma. En base al error, se ajustan los pesos y se realizan las modificaciones a estos lo que sea necesario.

In [18]:
epochs = 25000

for iteration in range(epochs):

    # Arranca con los valores de training
    input_layer = training_inputs

    # Genera un output haciendo la suma de los valores de input multiplicados por su peso sinaptico, y aplicandole la función sigmoide para normalizar a -1, 1
    outputs = forward(input_layer, synaptic_weights)

    # Calculo el error
    error = training_outputs - outputs

    # Ajusto los pesos en funcion al error y al resultado obtenido
    adjustments = error * sigmoid_derivative(outputs)
    synaptic_weights += np.dot(input_layer.T, adjustments)

## Backpropagation

En backpropagation, la idea es ajustar los pesos sinápticos en función del error calculado. Acá, se aplica la derivada de la función sigmoide a los valores de salida (sigmoid_derivative(outputs)) para medir la sensibilidad del error con respecto a los valores actuales de salida. Esto nos da una medida de cuánto ajustar los pesos en función del error y de la salida calculada. Esto se hace en la línea "adjustments = error * sigmoid_derivative(outputs)"

## Gradient Descent

Se usa gradient descent para actualizar los pesos (synaptic_weights) de la red. La actualización se hace sumando el producto de la matriz de las entradas rotadas (input_layer.T) y los ajustes calculados. Este es el paso que minimiza el error en cada iteración. Este paso se hace en la linea "synaptic_weights += np.dot(input_layer.T, adjustments)"

In [19]:
print('Synaptic weights after training')
print(synaptic_weights)

print('Outputs after training: ')
print(outputs)

Synaptic weights after training
[[-4.67948216  0.49035202  3.11811535]
 [ 2.82136849 -5.55808837 -2.02735712]
 [ 0.04525586  0.2178525  -0.83103881]
 [-0.73767219  0.67490215  1.94645695]
 [-0.0415763  -1.29789222  0.18606485]
 [-1.49869179  1.12063925  0.93787692]
 [-0.91932311  0.79488904 -0.54937554]
 [ 1.06743714  0.20814383  1.2250865 ]
 [-1.25950649  0.35050704 -0.49297425]
 [ 0.5954575   0.92066179  0.80975122]
 [-0.25267593 -0.97417258 12.34891723]]
Outputs after training: 
[[7.98565159e-01 4.34201679e-01 9.99891020e-01]
 [4.14813734e-01 5.50850145e-01 9.99998812e-01]
 [8.73376764e-01 3.27388135e-01 9.88221527e-01]
 [8.91810507e-01 7.44771580e-01 9.99927815e-01]
 [7.73069225e-01 7.93248480e-01 9.99975828e-01]
 [4.40657024e-01 1.44802053e-01 2.03500466e-02]
 [8.99439541e-01 1.60643165e-01 9.97121664e-01]
 [5.09111520e-01 4.44597825e-01 1.55785394e-01]
 [1.55189737e-01 6.63051475e-01 5.00113022e-01]
 [8.25364469e-01 2.67629410e-01 9.72054644e-01]
 [2.37509887e-01 7.55918062e-01 4

In [20]:
for i in range(100):
    print(outputs[i], training_outputs[i])

[0.79856516 0.43420168 0.99989102] [0 1 1]
[0.41481373 0.55085014 0.99999881] [1 1 1]
[0.87337676 0.32738814 0.98822153] [0 1 1]
[0.89181051 0.74477158 0.99992781] [0 0 1]
[0.77306923 0.79324848 0.99997583] [0 0 1]
[0.44065702 0.14480205 0.02035005] [1 0 1]
[0.89943954 0.16064317 0.99712166] [1 0 1]
[0.50911152 0.44459783 0.15578539] [0 1 0]
[0.15518974 0.66305147 0.50011302] [0 0 1]
[0.82536447 0.26762941 0.97205464] [0 1 1]
[0.23750989 0.75591806 0.42409754] [1 1 0]
[0.97309934 0.03755531 0.99997994] [1 0 1]
[0.30475816 0.73064439 0.98469128] [0 1 1]
[0.48263554 0.53423071 0.93285785] [1 1 1]
[0.91640421 0.06269817 0.98278632] [1 1 1]
[0.77862466 0.78903906 0.88725395] [0 1 1]
[0.59539509 0.6675058  0.99970178] [1 0 0]
[0.19176184 0.81428026 0.03856061] [0 0 1]
[0.44517914 0.72820081 0.82998393] [1 1 0]
[0.39661327 0.81178543 0.0164838 ] [1 1 0]
[3.43365770e-03 9.53852156e-01 4.99378191e-07] [1 0 1]
[0.57144356 0.37285395 0.99129295] [1 0 0]
[0.22009475 0.81827122 0.9623605 ] [1 0 1]

In [21]:
import numpy as np

# Lista de valores a procesar
valores = outputs

# Aplicar el umbral de 0.5 para convertir valores a 0 o 1
resultado = [[1 if valor > 0.5 else 0 for valor in fila] for fila in valores]

# Mostrar el resultado
print(np.array(resultado))


[[1 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 0 1]
 [1 0 0]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 1]
 [0 1 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]
 [1 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [1 0 1]
 [0 1 1]
 [0 0 1]
 [1 0 1]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 1]
 [1 1 1]
 [0 1 1]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [1 1 1]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 1]
 [1 0 1]
 [0 1 0]
 [0 0 0]
 [0 1 1]
 [0 1 0]
 [1 1 0]
 [1 1 0]
 [0 1 1]
 [0 0 0]
 [0 1 0]
 [1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]
 [1 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 1 1]
 [0 0 0]
 [0 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 0 0]
 [0 1 0]
 [0 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [1 0 1]
 [0 0 0]
 [1 0 1]
 [1 0 1]
 [1 1 1]
 [1 0 0]
 [0 1 1]
 [1 1 1]
 [0 1 0]
 [1 0 1]
 [0 1 0]
 [1 0 1]
 [1 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]
 [0 1 0]
 [0 1 1]
 [1 1 1]
 [0 1 1]
 [0 0 0]
 [1 1 1]
 [0 0 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 0 1]
 [1 0 1]
 

In [22]:
print("Outputs before training:")
print(training_outputs.T)
print("Outputs after training:")
print(resultado)

Outputs before training:
[[0 1 0 0 0 1 1 0 0 0 1 1 0 1 1 0 1 0 1 1 1 1 1 1 0 0 0 1 0 1 1 0 1 0 1 1
  1 1 0 0 0 1 1 1 0 0 0 1 0 0 1 0 1 1 1 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1
  0 0 1 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 1 1 1 1 0 1 0 0 1 0 0 0 0 0 1
  0 0 1 1 0 1 0 0 1 0 1 1 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 0 0 0 0 0 1 1
  1 1 0 1 1 1 0 0 1 1 1 0 1 0 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 1 0 0 0 0 0
  0 0 1 1 0 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 1 0 1 1 0 1 0
  1 1 0 0 0 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 1 0 0 0 0 1
  1 1 0 0 0 1 0 0 0 1 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 1 1 1 0 0 1 0 0 0 1 1
  0 0 1 0 0 1 0 1 1 0 1 0]
 [1 1 1 0 0 0 0 1 0 1 1 0 1 1 1 1 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 1 0
  1 1 1 1 0 0 1 1 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 1 0 0 0 1 0 1 1 1 0 0 1
  1 1 0 1 0 1 1 0 0 1 1 1 1 0 0 0 0 1 0 1 1 1 0 1 0 1 1 1 1 1 1 0 0 0 0 1
  0 1 1 1 0 0 1 1 0 1 1 0 1 0 1 1 0 1 0 0 1 0 1 1 1 1 0 0 0 0 0 1 1 1 1 0
  1 1 0 0 0 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 