# Trabajo Práctico Redes Neuronales

Trabajo Práctico hecho por Benjamin Kapustiansky y Oliver Safdieh

In [1]:
%pip install pandas
%pip install numpy
%pip install matplotlib
%pip install tabulate
%pip install networkx
%pip install random

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement random (from versions: none)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for random


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import HTML, display
import tabulate
import networkx as nx
from random import random as rand
import itertools

## Funciones

In [3]:
def sigmoid(x):
    return 1 / ( 1 + np.exp(-x) )

# sigmoid = lambda x : 1 / ( 1 + np.exp(-x) )

def sigmoid_derivative(x):
    return x * (1 - x)

# sigmoid_derivative = lambda x : x * (1 - x)

## Dataset

In [4]:
archivo = "dataset_frutas.csv"

# Leer datos del archivo
frutas : pd.DataFrame = pd.read_csv(archivo)
frutas

Peso      Color    Tamaño  Ácida  Dulce  Tropical
0    202.921570       Rojo  5.666598      0      1         1
1    162.004716      Verde  8.298573      1      1         1
2    179.362140   Amarillo  5.631649      0      1         1
3    217.226796   Amarillo  8.166169      0      0         1
4    206.026740      Claro  7.444632      0      0         1
..          ...        ...       ...    ...    ...       ...
295  184.106741     Oscuro  3.981108      1      0         0
296  152.931749       Rojo  7.602139      1      1         0
297  167.488610  Muy claro  7.751694      0      0         1
298  138.016529      Verde  5.637248      1      1         1
299  161.101677   Amarillo  8.441367      0      1         1

[300 rows x 6 columns]

## One Hot Encoding

In [5]:
# Color
frutas = pd.get_dummies(frutas, columns=["Color"])

frutas

Peso    Tamaño  Ácida  Dulce  Tropical  Color_Amarillo  \
0    202.921570  5.666598      0      1         1           False   
1    162.004716  8.298573      1      1         1           False   
2    179.362140  5.631649      0      1         1            True   
3    217.226796  8.166169      0      0         1            True   
4    206.026740  7.444632      0      0         1           False   
..          ...       ...    ...    ...       ...             ...   
295  184.106741  3.981108      1      0         0           False   
296  152.931749  7.602139      1      1         0           False   
297  167.488610  7.751694      0      0         1           False   
298  138.016529  5.637248      1      1         1           False   
299  161.101677  8.441367      0      1         1            True   

     Color_Claro  Color_Muy claro  Color_Muy oscuro  Color_Naranja  \
0          False            False             False          False   
1          False            False             False          False   
2          False            False             False          False   
3          False            False             False          False   
4           True            False             False          False   
..           ...              ...               ...            ...   
295        False            False             False          False   
296        False            False             False          False   
297        False             True             False          False   
298        False            False             False          False   
299        False            False             False          False   

     Color_Oscuro  Color_Rojo  Color_Rojo claro  Color_Verde  
0           False        True             False        False  
1           False       False             False         True  
2           False       False             False        False  
3           False       False             False        False  
4           False       False             False        False  
..            ...         ...               ...          ...  
295          True       False             False        False  
296         False        True             False        False  
297         False       False             False        False  
298         False       False             False         True  
299         False       False             False        False  

[300 rows x 14 columns]

## Reordenar columnas

In [6]:
frutas.columns

Index(['Peso', 'Tamaño', 'Ácida', 'Dulce', 'Tropical', 'Color_Amarillo',
       'Color_Claro', 'Color_Muy claro', 'Color_Muy oscuro', 'Color_Naranja',
       'Color_Oscuro', 'Color_Rojo', 'Color_Rojo claro', 'Color_Verde'],
      dtype='object')

In [7]:
frutas = frutas.reindex(['Peso', 'Tamaño', 'Color_Amarillo',
       'Color_Claro', 'Color_Muy claro', 'Color_Muy oscuro', 'Color_Naranja',
       'Color_Oscuro', 'Color_Rojo', 'Color_Rojo claro', 'Color_Verde', 'Ácida', 'Dulce', 'Tropical'], axis=1)
frutas


Peso    Tamaño  Color_Amarillo  Color_Claro  Color_Muy claro  \
0    202.921570  5.666598           False        False            False   
1    162.004716  8.298573           False        False            False   
2    179.362140  5.631649            True        False            False   
3    217.226796  8.166169            True        False            False   
4    206.026740  7.444632           False         True            False   
..          ...       ...             ...          ...              ...   
295  184.106741  3.981108           False        False            False   
296  152.931749  7.602139           False        False            False   
297  167.488610  7.751694           False        False             True   
298  138.016529  5.637248           False        False            False   
299  161.101677  8.441367            True        False            False   

     Color_Muy oscuro  Color_Naranja  Color_Oscuro  Color_Rojo  \
0               False          False         False        True   
1               False          False         False       False   
2               False          False         False       False   
3               False          False         False       False   
4               False          False         False       False   
..                ...            ...           ...         ...   
295             False          False          True       False   
296             False          False         False        True   
297             False          False         False       False   
298             False          False         False       False   
299             False          False         False       False   

     Color_Rojo claro  Color_Verde  Ácida  Dulce  Tropical  
0               False        False      0      1         1  
1               False         True      1      1         1  
2               False        False      0      1         1  
3               False        False      0      0         1  
4               False        False      0      0         1  
..                ...          ...    ...    ...       ...  
295             False        False      1      0         0  
296             False        False      1      1         0  
297             False        False      0      0         1  
298             False         True      1      1         1  
299             False        False      0      1         1  

[300 rows x 14 columns]

In [8]:
training_inputs = np.array(frutas[['Peso', 'Tamaño', 'Color_Amarillo', 'Color_Claro', 'Color_Muy claro', 'Color_Muy oscuro', 'Color_Naranja', 'Color_Oscuro', 'Color_Rojo', 'Color_Rojo claro', 'Color_Verde']])
training_outputs = np.array(frutas[['Ácida', 'Dulce', 'Tropical']])

display(training_inputs)
display(training_outputs)

array([[202.92157037902996, 5.666597658572325, False, ..., True, False,
        False],
       [162.0047162510167, 8.298572786946776, False, ..., False, False,
        True],
       [179.36213952317215, 5.631649267108148, True, ..., False, False,
        False],
       ...,
       [167.48861039259882, 7.751693972415556, False, ..., False, False,
        False],
       [138.01652912211375, 5.637247729450589, False, ..., False, False,
        True],
       [161.10167663542558, 8.441367139300942, True, ..., False, False,
        False]], dtype=object)

array([[0, 1, 1],
       [1, 1, 1],
       [0, 1, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 1],
       [1, 1, 0],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [0, 1, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 1, 0],
       [1, 1, 0],
       [1, 0, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 0],
       [1, 1, 0],
       [1, 0, 0],
       [0, 1, 1],
       [1, 0, 0],
       [0, 1, 1],
       [1, 1, 0],
       [1, 0, 0],
       [1, 1, 1],
       [1, 1, 0],
       [0, 1, 1],
       [0, 1, 0],
       [0, 0, 0],
       [1, 0, 1],
       [1, 1, 1],
       [1, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 1, 1],
       [0, 1, 1],
       [0, 0, 0],
       [1, 0, 1],
       [0, 0, 1],
       [1, 1, 0],
       [1, 0, 0],
       [1, 1, 1],
       [1,

In [9]:
training_values = np.concatenate((training_inputs.T, training_outputs.T)).T
table = lambda arr : display(HTML(tabulate.tabulate(arr, tablefmt='html')))
table(training_values)

In [10]:
input = training_inputs.shape[1]

In [11]:
output = training_outputs.shape[1]

In [12]:
synaptic_weights = np.random.random((input, output))

synaptic_weights

array([[0.62060061, 0.53467362, 0.30827723],
       [0.56368137, 0.69019479, 0.65420428],
       [0.1870945 , 0.46866447, 0.21638898],
       [0.44176115, 0.88263139, 0.82201661],
       [0.98624617, 0.63329492, 0.84441614],
       [0.85256233, 0.51693171, 0.9824061 ],
       [0.7348866 , 0.53099429, 0.00480074],
       [0.61295768, 0.04503754, 0.27353245],
       [0.96277072, 0.33690344, 0.88415566],
       [0.80913603, 0.5870357 , 0.91747007],
       [0.87907998, 0.18252619, 0.39470949]])

In [13]:
forward = lambda x, w: sigmoid(np.dot(x, w))

In [14]:
input_layer = training_inputs

# Genera un output haciendo la suma de los valores de input multiplicados por su peso sinaptico, y aplicandole la función sigmoide para normalizar a -1, 1
outputs = forward(input_layer, synaptic_weights)

outputs

TypeError: loop of ufunc does not support argument 0 of type float which has no callable exp method