# Trabajo Práctico Redes Neuronales

Trabajo Práctico hecho por Benjamin Kapustiansky y Oliver Safdieh

In [1]:
%pip install pandas
%pip install numpy
%pip install matplotlib
%pip install tabulate
%pip install networkx
%pip install random
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement random (from versions: none)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for random


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import HTML, display
import tabulate
import networkx as nx
from random import random as rand
import itertools

from sklearn.preprocessing import StandardScaler

## Funciones

In [3]:
def sigmoid(x):
    return 1 / ( 1 + np.exp(-x) )

# sigmoid = lambda x : 1 / ( 1 + np.exp(-x) )

def sigmoid_derivative(x):
    return x * (1 - x)

# sigmoid_derivative = lambda x : x * (1 - x)

## Dataset

In [4]:
archivo = "dataset_frutas.csv"

# Leer datos del archivo
frutas : pd.DataFrame = pd.read_csv(archivo)
frutas

Peso      Color    Tamaño  Ácida  Dulce  Tropical
0    202.921570       Rojo  5.666598      0      1         1
1    162.004716      Verde  8.298573      1      1         1
2    179.362140   Amarillo  5.631649      0      1         1
3    217.226796   Amarillo  8.166169      0      0         1
4    206.026740      Claro  7.444632      0      0         1
..          ...        ...       ...    ...    ...       ...
295  184.106741     Oscuro  3.981108      1      0         0
296  152.931749       Rojo  7.602139      1      1         0
297  167.488610  Muy claro  7.751694      0      0         1
298  138.016529      Verde  5.637248      1      1         1
299  161.101677   Amarillo  8.441367      0      1         1

[300 rows x 6 columns]

## One Hot Encoding

In [5]:
# Color
frutas = pd.get_dummies(frutas, columns=["Color"])

frutas

Peso    Tamaño  Ácida  Dulce  Tropical  Color_Amarillo  \
0    202.921570  5.666598      0      1         1           False   
1    162.004716  8.298573      1      1         1           False   
2    179.362140  5.631649      0      1         1            True   
3    217.226796  8.166169      0      0         1            True   
4    206.026740  7.444632      0      0         1           False   
..          ...       ...    ...    ...       ...             ...   
295  184.106741  3.981108      1      0         0           False   
296  152.931749  7.602139      1      1         0           False   
297  167.488610  7.751694      0      0         1           False   
298  138.016529  5.637248      1      1         1           False   
299  161.101677  8.441367      0      1         1            True   

     Color_Claro  Color_Muy claro  Color_Muy oscuro  Color_Naranja  \
0          False            False             False          False   
1          False            False             False          False   
2          False            False             False          False   
3          False            False             False          False   
4           True            False             False          False   
..           ...              ...               ...            ...   
295        False            False             False          False   
296        False            False             False          False   
297        False             True             False          False   
298        False            False             False          False   
299        False            False             False          False   

     Color_Oscuro  Color_Rojo  Color_Rojo claro  Color_Verde  
0           False        True             False        False  
1           False       False             False         True  
2           False       False             False        False  
3           False       False             False        False  
4           False       False             False        False  
..            ...         ...               ...          ...  
295          True       False             False        False  
296         False        True             False        False  
297         False       False             False        False  
298         False       False             False         True  
299         False       False             False        False  

[300 rows x 14 columns]

In [6]:
frutas.replace({True: 1, False: 0}, inplace=True)

frutas

C:\Users\48521682\AppData\Local\Temp\ipykernel_11964\4120693317.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  frutas.replace({True: 1, False: 0}, inplace=True)


Peso    Tamaño  Ácida  Dulce  Tropical  Color_Amarillo  \
0    202.921570  5.666598      0      1         1               0   
1    162.004716  8.298573      1      1         1               0   
2    179.362140  5.631649      0      1         1               1   
3    217.226796  8.166169      0      0         1               1   
4    206.026740  7.444632      0      0         1               0   
..          ...       ...    ...    ...       ...             ...   
295  184.106741  3.981108      1      0         0               0   
296  152.931749  7.602139      1      1         0               0   
297  167.488610  7.751694      0      0         1               0   
298  138.016529  5.637248      1      1         1               0   
299  161.101677  8.441367      0      1         1               1   

     Color_Claro  Color_Muy claro  Color_Muy oscuro  Color_Naranja  \
0              0                0                 0              0   
1              0                0                 0              0   
2              0                0                 0              0   
3              0                0                 0              0   
4              1                0                 0              0   
..           ...              ...               ...            ...   
295            0                0                 0              0   
296            0                0                 0              0   
297            0                1                 0              0   
298            0                0                 0              0   
299            0                0                 0              0   

     Color_Oscuro  Color_Rojo  Color_Rojo claro  Color_Verde  
0               0           1                 0            0  
1               0           0                 0            1  
2               0           0                 0            0  
3               0           0                 0            0  
4               0           0                 0            0  
..            ...         ...               ...          ...  
295             1           0                 0            0  
296             0           1                 0            0  
297             0           0                 0            0  
298             0           0                 0            1  
299             0           0                 0            0  

[300 rows x 14 columns]

## Reordenar columnas

In [7]:
frutas.columns

Index(['Peso', 'Tamaño', 'Ácida', 'Dulce', 'Tropical', 'Color_Amarillo',
       'Color_Claro', 'Color_Muy claro', 'Color_Muy oscuro', 'Color_Naranja',
       'Color_Oscuro', 'Color_Rojo', 'Color_Rojo claro', 'Color_Verde'],
      dtype='object')

In [8]:
frutas = frutas.reindex(['Peso', 'Tamaño', 'Color_Amarillo',
       'Color_Claro', 'Color_Muy claro', 'Color_Muy oscuro', 'Color_Naranja',
       'Color_Oscuro', 'Color_Rojo', 'Color_Rojo claro', 'Color_Verde', 'Ácida', 'Dulce', 'Tropical'], axis=1)
frutas


Peso    Tamaño  Color_Amarillo  Color_Claro  Color_Muy claro  \
0    202.921570  5.666598               0            0                0   
1    162.004716  8.298573               0            0                0   
2    179.362140  5.631649               1            0                0   
3    217.226796  8.166169               1            0                0   
4    206.026740  7.444632               0            1                0   
..          ...       ...             ...          ...              ...   
295  184.106741  3.981108               0            0                0   
296  152.931749  7.602139               0            0                0   
297  167.488610  7.751694               0            0                1   
298  138.016529  5.637248               0            0                0   
299  161.101677  8.441367               1            0                0   

     Color_Muy oscuro  Color_Naranja  Color_Oscuro  Color_Rojo  \
0                   0              0             0           1   
1                   0              0             0           0   
2                   0              0             0           0   
3                   0              0             0           0   
4                   0              0             0           0   
..                ...            ...           ...         ...   
295                 0              0             1           0   
296                 0              0             0           1   
297                 0              0             0           0   
298                 0              0             0           0   
299                 0              0             0           0   

     Color_Rojo claro  Color_Verde  Ácida  Dulce  Tropical  
0                   0            0      0      1         1  
1                   0            1      1      1         1  
2                   0            0      0      1         1  
3                   0            0      0      0         1  
4                   0            0      0      0         1  
..                ...          ...    ...    ...       ...  
295                 0            0      1      0         0  
296                 0            0      1      1         0  
297                 0            0      0      0         1  
298                 0            1      1      1         1  
299                 0            0      0      1         1  

[300 rows x 14 columns]

In [27]:
# Seleccionar las columnas a escalar (por ejemplo, 'columna1' y 'columna2')
columnas_a_escalar = ['Peso', 'Tamaño']

# Crear el scaler y aplicarlo solo a las columnas seleccionadas
scaler = StandardScaler()
frutas[columnas_a_escalar] = scaler.fit_transform(frutas[columnas_a_escalar])

frutas.head()

Peso    Tamaño  Color_Amarillo  Color_Claro  Color_Muy claro  \
0  1.735306 -0.712196               0            0                0   
1  0.372366  0.629630               0            0                0   
2  0.950542 -0.730013               1            0                0   
3  2.211812  0.562128               1            0                0   
4  1.838739  0.194277               0            1                0   

   Color_Muy oscuro  Color_Naranja  Color_Oscuro  Color_Rojo  \
0                 0              0             0           1   
1                 0              0             0           0   
2                 0              0             0           0   
3                 0              0             0           0   
4                 0              0             0           0   

   Color_Rojo claro  Color_Verde  Ácida  Dulce  Tropical  
0                 0            0      0      1         1  
1                 0            1      1      1         1  
2                 0            0      0      1         1  
3                 0            0      0      0         1  
4                 0            0      0      0         1

In [10]:
training_inputs = np.array(frutas[['Peso', 'Tamaño', 'Color_Amarillo', 'Color_Claro', 'Color_Muy claro', 'Color_Muy oscuro', 'Color_Naranja', 'Color_Oscuro', 'Color_Rojo', 'Color_Rojo claro', 'Color_Verde']])
training_outputs = np.array(frutas[['Ácida', 'Dulce', 'Tropical']]).T

display(training_inputs)
display(training_outputs)

array([[ 1.73530578, -0.71219616,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.37236649,  0.62963036,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 0.95054178, -0.73001346,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.55503485,  0.35082207,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.42667937, -0.72715926,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 0.34228626,  0.7024294 ,  1.        , ...,  0.        ,
         0.        ,  0.        ]])

array([[0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
        1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
        1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
        1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
        1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
        0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 

In [11]:
# training_values = np.concatenate((training_inputs.T, training_outputs.T)).T
# table = lambda arr : display(HTML(tabulate.tabulate(arr, tablefmt='html')))
# table(training_values)

In [12]:
input = training_inputs.shape[1]
input

11

In [13]:
output = training_outputs.shape[0]
output

3

In [14]:
synaptic_weights = np.random.random((input, output))

synaptic_weights

array([[0.11982702, 0.14924902, 0.05451133],
       [0.62132539, 0.59685494, 0.01969854],
       [0.00242976, 0.54516718, 0.12629516],
       [0.02169974, 0.22456342, 0.73518147],
       [0.53027237, 0.14143351, 0.76577073],
       [0.12532992, 0.67972652, 0.28189783],
       [0.86372616, 0.02443494, 0.27394926],
       [0.04991948, 0.45355707, 0.30108687],
       [0.45685922, 0.45507564, 0.21658226],
       [0.76211341, 0.39269419, 0.40784054],
       [0.18269247, 0.24095933, 0.09383193]])

In [15]:
forward = lambda x, w: sigmoid(np.dot(x, w))

In [16]:
input_layer = training_inputs

# Genera un output haciendo la suma de los valores de input multiplicados por su peso sinaptico, y aplicandole la función sigmoide para normalizar a -1, 1
outputs = forward(input_layer, synaptic_weights)

outputs

array([[0.55534484, 0.57174898, 0.57374489],
       [0.64988127, 0.66202528, 0.53159109],
       [0.41647872, 0.56250198, 0.54084137],
       [0.64947431, 0.77043819, 0.56412912],
       [0.5897034 , 0.64906877, 0.69830524],
       [0.47641322, 0.37920252, 0.6670883 ],
       [0.52832474, 0.44336268, 0.68982625],
       [0.45340633, 0.5883563 , 0.52777804],
       [0.48995386, 0.62627392, 0.56709886],
       [0.44569241, 0.26860613, 0.56440618],
       [0.79930173, 0.72382802, 0.6896913 ],
       [0.14258854, 0.24688565, 0.57281643],
       [0.54492728, 0.68080121, 0.57952143],
       [0.41344236, 0.46778276, 0.67440486],
       [0.39451773, 0.31750953, 0.68058828],
       [0.65085628, 0.56692532, 0.60322917],
       [0.52325218, 0.66791669, 0.58787684],
       [0.65066131, 0.75627174, 0.53348593],
       [0.674103  , 0.47568041, 0.5705458 ],
       [0.64541629, 0.55128875, 0.58855371],
       [0.81482068, 0.62947738, 0.54060223],
       [0.36498146, 0.5121718 , 0.57250884],
       [0.

In [17]:
training_outputs = training_outputs.T
training_outputs

array([[0, 1, 1],
       [1, 1, 1],
       [0, 1, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 1],
       [1, 1, 0],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [0, 1, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 1, 0],
       [1, 1, 0],
       [1, 0, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 0],
       [1, 1, 0],
       [1, 0, 0],
       [0, 1, 1],
       [1, 0, 0],
       [0, 1, 1],
       [1, 1, 0],
       [1, 0, 0],
       [1, 1, 1],
       [1, 1, 0],
       [0, 1, 1],
       [0, 1, 0],
       [0, 0, 0],
       [1, 0, 1],
       [1, 1, 1],
       [1, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 1, 1],
       [0, 1, 1],
       [0, 0, 0],
       [1, 0, 1],
       [0, 0, 1],
       [1, 1, 0],
       [1, 0, 0],
       [1, 1, 1],
       [1,

In [18]:
# Calculo el error
error = training_outputs - outputs
error

array([[-0.55534484,  0.42825102,  0.42625511],
       [ 0.35011873,  0.33797472,  0.46840891],
       [-0.41647872,  0.43749802,  0.45915863],
       [-0.64947431, -0.77043819,  0.43587088],
       [-0.5897034 , -0.64906877,  0.30169476],
       [ 0.52358678, -0.37920252,  0.3329117 ],
       [ 0.47167526, -0.44336268,  0.31017375],
       [-0.45340633,  0.4116437 , -0.52777804],
       [-0.48995386, -0.62627392,  0.43290114],
       [-0.44569241,  0.73139387,  0.43559382],
       [ 0.20069827,  0.27617198, -0.6896913 ],
       [ 0.85741146, -0.24688565,  0.42718357],
       [-0.54492728,  0.31919879,  0.42047857],
       [ 0.58655764,  0.53221724,  0.32559514],
       [ 0.60548227,  0.68249047,  0.31941172],
       [-0.65085628,  0.43307468,  0.39677083],
       [ 0.47674782, -0.66791669, -0.58787684],
       [-0.65066131, -0.75627174,  0.46651407],
       [ 0.325897  ,  0.52431959, -0.5705458 ],
       [ 0.35458371,  0.44871125, -0.58855371],
       [ 0.18517932, -0.62947738,  0.459

In [19]:
sigmoid_derivative(outputs)

array([[0.24693695, 0.24485208, 0.24456169],
       [0.2275356 , 0.22374781, 0.249002  ],
       [0.2430242 , 0.2460935 , 0.24833198],
       [0.22765743, 0.17686318, 0.24588746],
       [0.2419533 , 0.2277785 , 0.21067503],
       [0.24944366, 0.23540797, 0.2220815 ],
       [0.24919771, 0.24679221, 0.21396599],
       [0.24782903, 0.24219316, 0.24922838],
       [0.24989908, 0.2340549 , 0.24549774],
       [0.24705069, 0.19645688, 0.24585184],
       [0.16041847, 0.19990102, 0.21401721],
       [0.12225705, 0.18593313, 0.24469777],
       [0.24798154, 0.21731092, 0.24367634],
       [0.24250778, 0.24896205, 0.21958295],
       [0.23887349, 0.21669723, 0.21738787],
       [0.22724238, 0.245521  , 0.23934374],
       [0.24945934, 0.22180399, 0.24227766],
       [0.22730117, 0.1843248 , 0.24887869],
       [0.21968814, 0.24940856, 0.24502329],
       [0.2288541 , 0.24736946, 0.24215824],
       [0.15088794, 0.23323561, 0.24835146],
       [0.23176999, 0.24985185, 0.24474247],
       [0.

In [20]:
adjustments = error * sigmoid_derivative(outputs)
adjustments

array([[-0.13713516,  0.10485815,  0.10424567],
       [ 0.07966448,  0.0756211 ,  0.11663476],
       [-0.10121441,  0.10766542,  0.11402377],
       [-0.14785765, -0.13626215,  0.10717518],
       [-0.14268068, -0.14784391,  0.06355955],
       [ 0.13060541, -0.08926729,  0.07393353],
       [ 0.1175404 , -0.10941846,  0.06636663],
       [-0.11236725,  0.09969729, -0.13153727],
       [-0.12243902, -0.14658248,  0.10627625],
       [-0.11010862,  0.14368736,  0.10709154],
       [ 0.03219571,  0.05520706, -0.14760581],
       [ 0.10482459, -0.04590422,  0.10453086],
       [-0.13513191,  0.06936538,  0.10246068],
       [ 0.14224479,  0.1325019 ,  0.07149514],
       [ 0.14463366,  0.14789379,  0.06943624],
       [-0.14790213,  0.10632893,  0.09496461],
       [ 0.11892919, -0.14814658, -0.14242943],
       [-0.14789608, -0.13939963,  0.11610541],
       [ 0.07159571,  0.13076979, -0.13979701],
       [ 0.08114794,  0.11099746, -0.14252313],
       [ 0.02794133, -0.14681654,  0.114

In [21]:
np.dot(input_layer.T, adjustments)

array([[-2.91966965, -0.94696035,  0.10808338],
       [-6.67776622, -7.94301856, -1.34787717],
       [ 0.01127117, -0.44252975, -0.76325061],
       [-0.4464036 ,  0.54205152, -0.11126492],
       [-0.18885585, -1.13220258, -0.90349249],
       [-0.45306459, -0.01137881, -0.47907329],
       [-1.74080981,  0.30559814, -0.43013558],
       [ 0.47799299, -0.34091755,  0.23642949],
       [-1.54206773, -0.69306811, -0.75228845],
       [-0.84171341,  0.03527749, -0.71325179],
       [-0.70373984, -1.3110995 ,  1.2755899 ]])

In [22]:
epochs = 2500

for iteration in range(epochs):

    # Arranca con los valores de training
    input_layer = training_inputs

    # Genera un output haciendo la suma de los valores de input multiplicados por su peso sinaptico, y aplicandole la función sigmoide para normalizar a -1, 1
    outputs = forward(input_layer, synaptic_weights)

    # Calculo el error
    error = training_outputs - outputs

    # Ajusto los pesos en funcion al error y al resultado obtenido
    adjustments = error * sigmoid_derivative(outputs)
    synaptic_weights += np.dot(input_layer.T, adjustments)

In [23]:
print('Synaptic weights after training')
print(synaptic_weights)

print('Outputs after training: ')
print(outputs)

Synaptic weights after training
[[ 0.47104717  2.63322785  0.11229689]
 [-1.03398176 -0.53119833 -0.44172082]
 [ 0.51152024  0.76533778 -0.92267855]
 [-0.83706469  1.60138064  1.17614741]
 [-0.14721788 -1.00613808  1.17073925]
 [-1.57629675  1.13089478 -0.25485685]
 [-1.19372052  0.15094048 -0.4704272 ]
 [ 1.42349539  0.03498722  1.43660427]
 [-0.38438491  0.18775894  0.23895374]
 [ 1.18716663  2.04103273  1.00942214]
 [-0.32816357 -0.16016457 10.68163959]]
Outputs after training: 
[[9.97452692e-01 9.99733472e-01 9.67459354e-01]
 [2.27307891e-01 8.39744927e-01 9.99894094e-01]
 [9.93288563e-01 9.93005729e-01 8.78678505e-01]
 [9.90109290e-01 9.99987852e-01 3.17008094e-01]
 [9.75050832e-01 9.99958226e-01 9.15883003e-01]
 [4.70119056e-01 2.93810151e-03 9.22875440e-01]
 [9.93590501e-01 9.69667831e-01 9.83996107e-01]
 [6.71372911e-01 4.01304263e-01 4.37625415e-01]
 [2.97003422e-01 5.37628941e-01 6.29864223e-01]
 [9.95037011e-01 8.49247266e-01 9.94653776e-01]
 [3.33337440e-02 5.09843174e-01 5

In [24]:
for i in range(100):
    print(outputs[i], training_outputs[i])

[0.99745269 0.99973347 0.96745935] [0 1 1]
[0.22730789 0.83974493 0.99989409] [1 1 1]
[0.99328856 0.99300573 0.87867851] [0 1 1]
[0.99010929 0.99998785 0.31700809] [0 0 1]
[0.97505083 0.99995823 0.915883  ] [0 0 1]
[0.47011906 0.0029381  0.92287544] [1 0 1]
[0.9935905  0.96966783 0.98399611] [1 0 1]
[0.67137291 0.40130426 0.43762541] [0 1 0]
[0.29700342 0.53762894 0.62986422] [0 0 1]
[0.99503701 0.84924727 0.99465378] [0 1 1]
[0.03333374 0.50984317 0.05238066] [1 1 0]
[0.99999484 0.99909482 0.99998017] [1 0 1]
[0.70412714 0.98739008 0.66186318] [0 1 1]
[0.8032031  0.81580696 0.96620759] [1 1 1]
[0.99736029 0.70238933 0.99743706] [1 1 1]
[0.91729624 0.94196011 0.83390992] [0 1 1]
[0.97332941 0.99960574 0.88796134] [1 0 0]
[0.03965345 0.40550123 0.01628839] [0 0 1]
[0.65316306 0.8296503  0.66408208] [1 1 0]
[0.22158237 0.05195779 0.52951695] [1 1 0]
[6.44750472e-06 6.97930477e-06 1.20435208e-03] [1 0 1]
[0.98037624 0.97333165 0.98118294] [1 0 0]
[0.38520811 0.98507176 0.19002626] [1 0 1]

In [28]:
import numpy as np

# Lista de valores a procesar
valores = outputs

# Aplicar el umbral de 0.5 para convertir valores a 0 o 1
resultado = [[1 if valor > 0.5 else 0 for valor in fila] for fila in valores]

# Mostrar el resultado
print(np.array(resultado))


[[1 1 1]
 [0 1 1]
 [1 1 1]
 [1 1 0]
 [1 1 1]
 [0 0 1]
 [1 1 1]
 [1 0 0]
 [0 1 1]
 [1 1 1]
 [0 1 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]
 [0 0 1]
 [0 0 0]
 [1 1 1]
 [0 1 0]
 [0 0 1]
 [1 1 1]
 [0 0 0]
 [0 1 0]
 [1 0 1]
 [1 1 1]
 [1 1 0]
 [0 1 0]
 [0 1 1]
 [0 0 0]
 [1 0 1]
 [0 0 1]
 [1 1 1]
 [1 1 0]
 [1 1 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 0 1]
 [0 0 1]
 [0 0 1]
 [1 1 1]
 [0 0 0]
 [0 0 0]
 [1 0 1]
 [0 1 0]
 [1 0 1]
 [0 0 0]
 [1 0 1]
 [1 1 1]
 [1 0 1]
 [1 1 1]
 [1 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 1]
 [0 0 0]
 [1 1 1]
 [1 0 1]
 [0 1 1]
 [1 1 1]
 [0 1 0]
 [1 1 1]
 [1 0 1]
 [0 1 1]
 [0 0 0]
 [1 0 1]
 [0 0 0]
 [1 0 1]
 [0 0 0]
 [0 0 0]
 [1 1 0]
 [1 1 1]
 [1 0 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 0 1]
 [0 0 1]
 [1 1 0]
 [0 0 0]
 [1 1 1]
 [0 1 0]
 [1 1 1]
 [1 1 1]
 [0 1 0]
 [1 0 1]
 [1 1 1]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [0 0 1]
 [1 0 1]
 [1 1 1]
 [0 0 1]
 [1 1 1]
 [0 0 0]
 [0 0 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 

In [ ]:
print("Outputs before training:")
outputs
print("Outputs after training:")
resultado

Outputs before training:
Outputs after training:


[[1, 1, 1],
 [0, 1, 1],
 [1, 1, 1],
 [1, 1, 0],
 [1, 1, 1],
 [0, 0, 1],
 [1, 1, 1],
 [1, 0, 0],
 [0, 1, 1],
 [1, 1, 1],
 [0, 1, 0],
 [1, 1, 1],
 [1, 1, 1],
 [1, 1, 1],
 [1, 1, 1],
 [1, 1, 1],
 [1, 1, 1],
 [0, 0, 0],
 [1, 1, 1],
 [0, 0, 1],
 [0, 0, 0],
 [1, 1, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 1, 1],
 [0, 0, 0],
 [0, 1, 0],
 [1, 0, 1],
 [1, 1, 1],
 [1, 1, 0],
 [0, 1, 0],
 [0, 1, 1],
 [0, 0, 0],
 [1, 0, 1],
 [0, 0, 1],
 [1, 1, 1],
 [1, 1, 0],
 [1, 1, 1],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [1, 1, 1],
 [1, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 1, 1],
 [0, 0, 0],
 [0, 0, 0],
 [1, 0, 1],
 [0, 1, 0],
 [1, 0, 1],
 [0, 0, 0],
 [1, 0, 1],
 [1, 1, 1],
 [1, 0, 1],
 [1, 1, 1],
 [1, 0, 1],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 1],
 [0, 1, 1],
 [1, 0, 1],
 [0, 0, 0],
 [1, 1, 1],
 [1, 0, 1],
 [0, 1, 1],
 [1, 1, 1],
 [0, 1, 0],
 [1, 1, 1],
 [1, 0, 1],
 [0, 1, 1],
 [0, 0, 0],
 [1, 0, 1],
 [0, 0, 0],
 [1, 0, 1],
 [0, 0, 0],
 [0, 0, 0],
 [1, 1, 0],
 [1, 1, 1],
 [1,